import React from "react";
import TrueFalseQuestions from "../../../../components/games/true-false/trueFalseQuestions";
import { TrueFalseQuestion } from "../../../../components/games/model";

const quesitons: TrueFalseQuestion[] = [
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },

  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },

  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },

  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },

  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },

  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
  {
    text: "Fearless album came out in 2014",
    swipeLeftAnswer: "False god",
    swipeRightAnswer: "True love",
    image: "/album-taylor-swift.png",
    correctAnswer: "left",
    correctAnswerText: "Fearless album came out in 2008",
  },
];
const SwipeGamePage: React.FC = () => {
  return <TrueFalseQuestions {...{ questions: quesitons }} />;
};

export default SwipeGamePage;
