import React from "react";
import TrueFalseQuestions from "../../../../components/games/true-false/trueFalseQuestions";
import { Question } from "../../../../models/question";

const quesitons: Question[] = [
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },

  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },

  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },

  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },

  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },

  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
  {
    title: "Fearless album came out in 2014",
    image: "/album-taylor-swift.png",
    answer: "false",
    content: "Fearless album came out in 2008",
    type: "swipe",
  },
];
const SwipeGamePage: React.FC = () => {
  return <TrueFalseQuestions {...{ questions: quesitons }} />;
};

export default SwipeGamePage;
